# Generated by Django 2.2 on 2020-06-09 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('category', '0001_initial'),
        ('seller', '0001_initial'),
        ('randomid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='category.Category')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='randomid.randomId')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.Seller')),
            ],
        ),
    ]
